### ISSUE TITLE
Generated FMU does not work

### ISSUE THREAD

**Issue by HenningScheufler** [Vico-platform/fmu4j_template#1]
build FMU:

```
gradlew.bat build fmu
```

java --version

```
openjdk version "1.8.0_302"
```

Error message opening the fmu with fmpy.

```
python -m fmpy.gui -> open fmu with gui and on click run
```

![image](https://user-images.githubusercontent.com/16381681/140314222-7661a2cd-3b04-4853-8cc1-9d6155d0deed.png)

Can you reproduce the error?
@markaren 

It might be useful to add this repo as an example to fmu4j

**Comment by markaren** [comment]
No, I can't reproduce. Can you use Dependency walker or similar to figure out what DLL you are missing on system PATH?

**Comment by HenningScheufler** [comment]
setting the JAVA_HOME was not sufficient the path also needs to contain the folder with libjvm.dll in my case (JAVA_HOME \jre\bin\server)
